# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b89a2c968c6d58f5680535f65c2db7e9c04e21482e089a9beaed6adfb05d22415fd5b45d9c96dfa39b7ed18fec7a169ef17c0b6307579b3df89b0b78d40358a3
  square_application_id: <%= ENV['SQUARE_APPLICATION_ID'] %>
  square_access_token: <%= ENV['SQUARE_ACCESS_TOKEN'] %>
  square_location_id: <%= ENV['SQUARE_LOCATION_ID'] %>

test:
  secret_key_base: 591fd52020e24bafb3f94ce9cbc67405b466d37b2f5dcd145aa6ec169245c5feb96b71d644c1fa3df9ca2e56827c12b45329510fdf56d35aba4a722f3c69b794
  square_application_id: <%= ENV['SQUARE_APPLICATION_ID'] %>
  square_access_token: <%= ENV['SQUARE_ACCESS_TOKEN'] %>
  square_location_id: <%= ENV['SQUARE_LOCATION_ID'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  square_application_id: <%= ENV['SQUARE_APPLICATION_ID'] %>
  square_access_token: <%= ENV['SQUARE_ACCESS_TOKEN'] %>
  square_location_id: <%= ENV['SQUARE_LOCATION_ID'] %>
